### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by hfiguiere** [flathub/app.getspace.Space#1]
I did retrigger the previously failed build because the tarball was "403", but after checking it was ok.

Hoewever the build failed this time because the checksum doesn't match:

https://buildbot.flathub.org/#/builders/12/builds/12075

**Comment by friebetill** [comment]
Thanks for the hint! I had an error in my continuous deployment and had then manually uploaded the tarball on AWS. Apparently I made a mistake and put the wrong shasum in `app.getspace.Space.json`, because `1c050f75a98575dcd0d762d5269a88646cc05a625283c20d2f93abba2539f95f` is the correct shasum. I have now released the new version 2.0.5 with the correct shasum.
